# ---- Build Stage ----
FROM node:24-alpine AS build

WORKDIR /app

# # Install system dependencies for sharp
# RUN apk add --no-cache \
#   vips-dev \
#   build-base \
#   python3

# Enable Yarn (via Corepack)
RUN corepack enable

# Copy package files and install dependencies
COPY .yarnrc.yml ./
COPY package.json yarn.lock ./
RUN yarn install

# Copy the rest of the app
COPY . .

# ---- Production Stage ----
FROM node:24-alpine AS prod

WORKDIR /app

# # Install only runtime dependencies for sharp
# RUN apk add --no-cache \
#   vips-dev \
#   python3

# Enable Yarn (via Corepack)
RUN corepack enable

# Copy only necessary files from build stage
COPY --from=build /app ./

EXPOSE 3000
CMD ["yarn", "dev"] # or whatever your start command is
