on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd shopee-tool
            git checkout .
            git pull origin master
            node --version
            sudo yarn add sharp --ignore-engines
            yarn install
            sudo pm2 restart all
